# Generated by Django 4.2.11 on 2024-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_cpu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmconfig',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
