# Generated by Django 4.2.11 on 2024-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_cpu', '0003_alter_vmconfig_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmconfig',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vmconfig',
            name='public_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vmconfig',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
