# Generated by Django 4.2.11 on 2024-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_cpu', '0004_vmconfig_file_vmconfig_public_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmconfig',
            name='file',
            field=models.FileField(null=True, upload_to='uploads_midel'),
        ),
    ]
